pull_request_rules:
  - name: Automatic merge when CI passes and no unresolved reviews
    conditions:
      - check-success = lint
      - check-success = test
      - check-success = coverage
      - "#review-threads-unresolved = 0"
      - label = automerge
    actions:
      merge:
        method: squash
