name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-env

      - name: Lint
        run: sbt scalafmtSbtCheck scalafmtCheckAll borsh4sJVM/compile

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-env

      - name: Test
        run: sbt borsh4sJS/test borsh4sNative/test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-env

      - name: Coverage report
        run: sbt coverage borsh4sJVM/test borsh4sJVM/coverageReport
